### ISSUE TITLE
SQLite won't install properly

### ISSUE THREAD

**Issue by axelkennedal** [sjmelia/electron-boilerplate-sqlite#12]
When running `npm install` after cloning your repo I get the following errors:

```
> sqlite3@3.1.13 install /Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: Empty target version is not supported if electron is the target.
node-pre-gyp ERR! stack     at get_electron_abi (/Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:34:15)
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:81:16)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:292:19)
node-pre-gyp ERR! stack     at handle_gyp_opts (/Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js:54:27)
node-pre-gyp ERR! stack     at configure (/Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/configure.js:11:5)
node-pre-gyp ERR! stack     at /Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/build.js:35:13
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:85:9)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.11.0/bin/node" "/Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/axelkennedal/SyncBoi/Programmering/Electron/electron-boilerplate-sqlite/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN electron-boilerplate-sqlite@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'm running this on macOS Mojave.

**Comment by anasred** [comment]
same here 👎

**Comment by anasred** [comment]
I solve it out by downgrading python to version 2.7.X

**Comment by axelkennedal** [comment]
@anasred gotcha, I already opted to use lowdb instead 🤷‍♂️

**Comment by sjmelia** [comment]
Thanks @anasred for helping out and glad you found (some kind of!) a solution @axelkennedal !
